### ISSUE TITLE
About obtaining edge_GT！

### ISSUE THREAD

**Issue by Lee-zl** [laprf/SMN#1]
作者您好！有一个关于edge_GT获取的问题。README中提到edge_GT是通过pidinet生成的，但这涉及到另一个网络的训练和生成，可能会影响最后模型测试精度。为了能够尽可能复现您论文里的精度，想请问下HS-SOD和HSOD-BIT的这两个数据集的edge_GT方便提供一下吗？万分感谢！！！

**Comment by laprf** [comment]
感谢对于我们工作的关注！我们已经更新了README，并在网盘中提供了edge_GT，请查收。
